name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      APP_URL: "https://demoqa.com/"
      USER_NAME: abmercado19
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run: |
          pipenv install --dev  # Install dependencies from Pipfile.lock

      - name: Run tests
        run: |
          pipenv run behavex --define BASE_URL="${BASE_URL}" --define USERNAME="${USERNAME}" --define PASSWORD="${PASSWORD}"
